# DataFrame row index, data조작, index조작

- loc() : 라벨기반의 2차원 인덱싱
- iloc() : 정수값 기반의 2차원 인덱싱

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json

import warnings
warnings.filterwarnings(action = 'ignore') 

from datetime import date, datetime, timedelta
from dateutil.parser import parse

print("numpy version:",np.__version__) 
print("pandas version:",pd.__version__)

numpy version: 1.20.1
pandas version: 1.2.4


In [2]:
def seriesInfo(ary):
    print('data \n', ary)
    print('index : ', type(ary.index), ary.index)
    print('value : ', type(ary.values), ary.values)
    
def frmInfo(df):
    display('DataFrame',df)
    print('shape : ', df.shape) # 형태
    print('size : ' , df.size) # 전체 개수
    print('ndim : ' , df.ndim)
    print('index(row) : ', df.index, type(df.index)) # row index
    print('columns : ', df.columns, type(df.columns))
    print('values : \n', df.values, type(df.values))

In [4]:
sample_frm = pd.DataFrame(np.arange(10, 22).reshape(3,4),
                         index=['a','b','c'],
                         columns=['col01','col02','col03','col04'])
frmInfo(sample_frm)

'DataFrame'

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

shape :  (3, 4)
size :  12
ndim :  2
index(row) :  Index(['a', 'b', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]] <class 'numpy.ndarray'>


In [7]:
# loc, iloc
seriesInfo(sample_frm.loc['a'])
print(sample_frm.loc['a'].values, type(sample_frm.loc['a'].values))

data 
 col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32
index :  <class 'pandas.core.indexes.base.Index'> Index(['col01', 'col02', 'col03', 'col04'], dtype='object')
value :  <class 'numpy.ndarray'> [10 11 12 13]
[10 11 12 13] <class 'numpy.ndarray'>


#### loc함수 : 행 또는 행과 열의 라벨링이 들어가야 함!! 
- 열의 라벨링만 들어가면 오류남! 

#### iloc함수 : 행 또는 행과 열의 정수인덱스가 들어가야 함!!
- 열의 정수인덱스만 들어가면 오류남!

In [9]:
frmInfo(sample_frm.loc[['a','c']])
frmInfo(sample_frm.iloc[[0,2]])

'DataFrame'

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

shape :  (2, 4)
size :  8
ndim :  2
index(row) :  Index(['a', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[10 11 12 13]
 [18 19 20 21]] <class 'numpy.ndarray'>


'DataFrame'

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

shape :  (2, 4)
size :  8
ndim :  2
index(row) :  Index(['a', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[10 11 12 13]
 [18 19 20 21]] <class 'numpy.ndarray'>


In [10]:
seriesInfo(sample_frm['col01'])

data 
 a    10
b    14
c    18
Name: col01, dtype: int32
index :  <class 'pandas.core.indexes.base.Index'> Index(['a', 'b', 'c'], dtype='object')
value :  <class 'numpy.ndarray'> [10 14 18]


In [11]:
sample_frm['col01']>15

a    False
b    False
c     True
Name: col01, dtype: bool

In [12]:
sample_frm.loc[sample_frm['col01']>15] # boolean indexing

col01  col02  col03  col04
c     18     19     20     21

In [14]:
print(type(sample_frm.loc['a','col01']),sample_frm.loc['a','col01'])

<class 'numpy.int32'> 10


In [16]:
print(type(sample_frm.loc['a':'b','col01']),"\n",sample_frm.loc['a':'b','col01']) # 슬라이싱 가능

<class 'pandas.core.series.Series'> 
 a    10
b    14
Name: col01, dtype: int32


In [17]:
print(type(sample_frm.loc['a',:]),"\n",sample_frm.loc['a',:]) # 슬라이싱 가능

<class 'pandas.core.series.Series'> 
 col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32


In [18]:
print(type(sample_frm.loc['a',['col03','col04']]),"\n",sample_frm.loc['a',['col03','col04']]) # 열 여러개 선택가능

<class 'pandas.core.series.Series'> 
 col03    12
col04    13
Name: a, dtype: int32


In [21]:
sample_frm.iloc[0,-2:]

col03    12
col04    13
Name: a, dtype: int32

In [22]:
sample_frm.iloc[-1]=sample_frm.iloc[-1] * 2 # 행 데이터 갱신
frmInfo(sample_frm)

'DataFrame'

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42

shape :  (3, 4)
size :  12
ndim :  2
index(row) :  Index(['a', 'b', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[10 11 12 13]
 [14 15 16 17]
 [36 38 40 42]] <class 'numpy.ndarray'>


In [23]:
# 행추가
sample_frm.loc['d']=0
frmInfo(sample_frm)

'DataFrame'

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42
d      0      0      0      0

shape :  (4, 4)
size :  16
ndim :  2
index(row) :  Index(['a', 'b', 'c', 'd'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[10 11 12 13]
 [14 15 16 17]
 [36 38 40 42]
 [ 0  0  0  0]] <class 'numpy.ndarray'>


In [24]:
# 기존 행을 복사해서 새로운 행으로 추가
sample_frm.loc['e']=sample_frm.loc['d']
frmInfo(sample_frm)

'DataFrame'

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42
d      0      0      0      0
e      0      0      0      0

shape :  (5, 4)
size :  20
ndim :  2
index(row) :  Index(['a', 'b', 'c', 'd', 'e'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[10 11 12 13]
 [14 15 16 17]
 [36 38 40 42]
 [ 0  0  0  0]
 [ 0  0  0  0]] <class 'numpy.ndarray'>


In [26]:
sample_frm['col05']=sample_frm['col04']
frmInfo(sample_frm)

'DataFrame'

col01  col02  col03  col04  col05
a     10     11     12     13     13
b     14     15     16     17     17
c     36     38     40     42     42
d      0      0      0      0      0
e      0      0      0      0      0

shape :  (5, 5)
size :  25
ndim :  2
index(row) :  Index(['a', 'b', 'c', 'd', 'e'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['col01', 'col02', 'col03', 'col04', 'col05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[10 11 12 13 13]
 [14 15 16 17 17]
 [36 38 40 42 42]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]] <class 'numpy.ndarray'>


In [29]:
print(sample_frm.iloc[1,1],sample_frm.iloc[1][1]) # 같은 결과

15 15


In [62]:
score_data = {
    'kor'  : [80,90,70,30],
    'eng'  : [90,70,60,40],
    'math' : [90,60,90,70] 
}
columns = ['kor','eng','math']
index   = ['김지은', '황인범', '김정수', '최호진']

score_frm = pd.DataFrame(score_data, index=index, columns=columns)
frmInfo(score_frm)

'DataFrame'

kor  eng  math
김지은   80   90    90
황인범   90   70    60
김정수   70   60    90
최호진   30   40    70

shape :  (4, 3)
size :  12
ndim :  2
index(row) :  Index(['김지은', '황인범', '김정수', '최호진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['kor', 'eng', 'math'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[80 90 90]
 [90 70 60]
 [70 60 90]
 [30 40 70]] <class 'numpy.ndarray'>


In [63]:
# 모든 학생의 각 과목 평균 점수를 새로운 열로 추가하라
score_frm['mean']= round((score_frm['kor']+score_frm['eng']+score_frm['math'])/3,2)
frmInfo(score_frm)
# 다른 방법 : score_frm['average']=np.mean(score_frm, axis=1).round(2)

'DataFrame'

kor  eng  math   mean
김지은   80   90    90  86.67
황인범   90   70    60  73.33
김정수   70   60    90  73.33
최호진   30   40    70  46.67

shape :  (4, 4)
size :  16
ndim :  2
index(row) :  Index(['김지은', '황인범', '김정수', '최호진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['kor', 'eng', 'math', 'mean'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[80.   90.   90.   86.67]
 [90.   70.   60.   73.33]
 [70.   60.   90.   73.33]
 [30.   40.   70.   46.67]] <class 'numpy.ndarray'>


In [64]:
# 최호진 학생의 영어 점수를 90점으로 수정하고 평균 점수도 다시 계산하라
score_frm.loc['최호진','eng']=90
score_frm['mean']= round((score_frm['kor']+score_frm['eng']+score_frm['math'])/3,2)
frmInfo(score_frm)

'DataFrame'

kor  eng  math   mean
김지은   80   90    90  86.67
황인범   90   70    60  73.33
김정수   70   60    90  73.33
최호진   30   90    70  63.33

shape :  (4, 4)
size :  16
ndim :  2
index(row) :  Index(['김지은', '황인범', '김정수', '최호진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['kor', 'eng', 'math', 'mean'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[80.   90.   90.   86.67]
 [90.   70.   60.   73.33]
 [70.   60.   90.   73.33]
 [30.   90.   70.   63.33]] <class 'numpy.ndarray'>


In [65]:
# 김지은 학생의 점수를 데이터 프레임으로 만들어라
jieun_df = pd.DataFrame(score_frm.loc['김지은'])
jieun_df 

김지은
kor   80.00
eng   90.00
math  90.00
mean  86.67

In [66]:
# 김정수 학생의 점수를 시리즈로 출력하라
print(score_frm.loc['김정수'],type(score_frm.loc['김정수']))

kor     70.00
eng     60.00
math    90.00
mean    73.33
Name: 김정수, dtype: float64 <class 'pandas.core.series.Series'>


In [67]:
# 황인범 학생의 국어점수와 수학점수를 100점으로 수정하고 평균 점수도 다시 계산하라
score_frm.loc['황인범',['kor','math']]=100
score_frm['mean']=np.mean(score_frm[['kor','eng','math']], axis=1).round(2)
frmInfo(score_frm)

'DataFrame'

kor  eng  math   mean
김지은   80   90    90  86.67
황인범  100   70   100  90.00
김정수   70   60    90  73.33
최호진   30   90    70  63.33

shape :  (4, 4)
size :  16
ndim :  2
index(row) :  Index(['김지은', '황인범', '김정수', '최호진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns :  Index(['kor', 'eng', 'math', 'mean'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[ 80.    90.    90.    86.67]
 [100.    70.   100.    90.  ]
 [ 70.    60.    90.    73.33]
 [ 30.    90.    70.    63.33]] <class 'numpy.ndarray'>


## 데이터 프레임 조작, count()

In [71]:
tmp_series=pd.Series(range(10))
tmp_series[5] = np.NaN # null값으로 1개 수정
tmp_series

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    NaN
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [72]:
# count()
tmp_series.count() # null값 제외하고 count해줌.

9

In [74]:
cnt_frm=pd.DataFrame(np.random.randint(5,size=(4,4)))
cnt_frm

0  1  2  3
0  2  4  2  0
1  4  3  2  1
2  0  2  2  0
3  4  1  1  2

In [75]:
cnt_frm.count() # 0열에 4개, 1열에 4개, 2열에 4개, 3열에 4개

0    4
1    4
2    4
3    4
dtype: int64

In [76]:
cnt_frm.iloc[1,0]=np.NaN
cnt_frm.iloc[3,0]=np.NaN
cnt_frm.iloc[2,3]=np.NaN
cnt_frm

0  1  2    3
0  2.0  4  2  0.0
1  NaN  3  2  1.0
2  0.0  2  2  NaN
3  NaN  1  1  2.0

In [77]:
cnt_frm.count()  # 0열에 2개, 1열에 4개, 2열에 4개, 3열에 3개

0    2
1    4
2    4
3    3
dtype: int64

## [타이타닉 데이터를 이용한 실습]

In [80]:
import seaborn as sns
datasets=sns.load_dataset('titanic') # 내장데이터 활용하는 방법
print("type",type(datasets))

type <class 'pandas.core.frame.DataFrame'>


In [81]:
# csv파일을 불러와서 활용하는 방법
titanic_dataset=pd.read_csv('C:/Users/whgud/data/titanic_train.csv')
print("type",type(titanic_dataset))

type <class 'pandas.core.frame.DataFrame'>


In [82]:
frmInfo(datasets)

'DataFrame'

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

shape :  (891, 15)
size :  13365
ndim :  2
index(row) :  RangeIndex(start=0, stop=891, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns :  Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[0 3 'male' ... 'Southampton' 'no' False]
 [1 1 'female' ... 'Cherbourg' 'yes' False]
 [1 3 'female' ... 'Southampton' 'yes' True]
 ...
 [0 3 'female' ... 'Southampton' 'no' False]
 [1 1 'male' ... 'Cherbourg' 'yes' True]
 [0 3 'male' ... 'Queenstown' 'no' True]] <class 'numpy.ndarray'>


In [83]:
frmInfo(titanic_dataset) # data가 약간 다름.

'DataFrame'

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

shape :  (891, 12)
size :  10692
ndim :  2
index(row) :  RangeIndex(start=0, stop=891, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns :  Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>
values : 
 [[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']] <class 'numpy.ndarray'>


In [84]:
datasets.info() # 데이터셋에 대한 이해를 위해

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [85]:
datasets.head() # 위에서부터 5줄

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [86]:
datasets.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [87]:
datasets['class'].value_counts() # 그룹별 count를 구할때

Third     491
First     216
Second    184
Name: class, dtype: int64

In [89]:
datasets['class'].value_counts().values # 그룹별 count의 value값만 필요할때

array([491, 216, 184], dtype=int64)

In [90]:
# age_by_10 컬럼 추가하고자 한다
# age 컬럼의 값에 10살을 더한 값으로 일괄 적용한다
datasets['age_by_10'] = datasets['age']+10
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  
0    man        True  NaN  Southampton    no  False       32.0  
1  woman       False    C    Cherbourg   yes  False       48.0  
2  woman       False  NaN  Southampton   yes   True       36.0  
3  woman       False    C  Southampton   yes  False       45.0  
4    man        True  NaN  Southampton    no   True       45.0

In [91]:
# parch와 sibSp의 값과 1을 더한 family_no 컬럼 생성
datasets['family_no']=datasets['parch'] + datasets['sibsp']+1
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False       32.0          2  
1  woman       False    C    Cherbourg   yes  False       48.0          2  
2  woman       False  NaN  Southampton   yes   True       36.0          1  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1

# 새로 만든 두개의 컬럼을 삭제한다면?
- drop(label, axis=, inplace=True) 
- inplace=True인 경우, 원본데이터에서 삭제, False인 경우 삭제된 새로운 data리턴
- axis=1 (열), axis=0(행)

In [92]:
datasets_drop_frm = datasets.drop(['age_by_10','family_no'],axis=1,inplace=False)
datasets_drop_frm.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [93]:
datasets.head() # 원본데이터에서는 삭제안됐음! 

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False       32.0          2  
1  woman       False    C    Cherbourg   yes  False       48.0          2  
2  woman       False  NaN  Southampton   yes   True       36.0          1  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1

In [94]:
# 만약 3개 행을 삭제하고 싶다면?
datasets_drop_frm=datasets.drop([0,1,2],axis=0,inplace=False)
datasets_drop_frm.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1  
5    man        True  NaN   Queenstown    no   True        NaN          1  
6    man        True    E  Southampton    no   True       64.0          1  
7  child       False  NaN  Southampton    no  False       12.0          5

In [95]:
datasets.index[:10].values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [97]:
fare_series=datasets['fare']
print("type:",type(fare_series))
print("values type:",type(fare_series.values))
print('values',fare_series.values)

type: <class 'pandas.core.series.Series'>
values type: <class 'numpy.ndarray'>
values [  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.287

In [98]:
print("max:",fare_series.max())
print("min:",fare_series.min())
print("sum:",fare_series.sum())

max: 512.3292
min: 0.0
sum: 28693.9493


### 인덱스를 재정의하는 방법
- reset_index():새로운 인덱스 할당, 기존 인덱스를 열로 추가하는 방법

In [99]:
datasets_drop_frm # 인덱스가 3부터 시작되고 있는 상태

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
5           0       3    male   NaN      0      0   8.4583        Q   Third   
6           0       1    male  54.0      0      0  51.8625        S   First   
7           0       3    male   2.0      3      1  21.0750        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
3    woman       False    C  Southampton   yes  False       45.0          2  
4      man        True  NaN  Southampton    no   True       45.0          1  
5      man        True  NaN   Queenstown    no   True        NaN          1  
6      man        True    E  Southampton    no   True       64.0          1  
7    child       False  NaN  Southampton    no  False       12.0          5  
..     ...         ...  ...          ...   ...    ...        ...        ...  
886    man        True  NaN  Southampton    no   True       37.0          1  
887  woman       False    B  Southampton   yes   True       29.0          1  
888  woman       False  NaN  Southampton    no  False        NaN          4  
889    man        True    C    Cherbourg   yes   True       36.0          1  
890    man        True  NaN   Queenstown    no   True       42.0          1  

[888 rows x 17 columns]

In [105]:
reset_index_frm=datasets_drop_frm.reset_index(inplace=False) # 인덱스가 초기화해서 새 변수에 담기
reset_index_frm.head()

index  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0      3         1       1  female  35.0      1      0  53.1000        S   
1      4         0       3    male  35.0      0      0   8.0500        S   
2      5         0       3    male   NaN      0      0   8.4583        Q   
3      6         0       1    male  54.0      0      0  51.8625        S   
4      7         0       3    male   2.0      3      1  21.0750        S   

   class    who  adult_male deck  embark_town alive  alone  age_by_10  \
0  First  woman       False    C  Southampton   yes  False       45.0   
1  Third    man        True  NaN  Southampton    no   True       45.0   
2  Third    man        True  NaN   Queenstown    no   True        NaN   
3  First    man        True    E  Southampton    no   True       64.0   
4  Third  child       False  NaN  Southampton    no  False       12.0   

   family_no  
0          2  
1          1  
2          1  
3          1  
4          5

In [109]:
# pclass, fare열만 추출해보기
datasets[['pclass','fare']] 

pclass     fare
0         3   7.2500
1         1  71.2833
2         3   7.9250
3         1  53.1000
4         3   8.0500
..      ...      ...
886       2  13.0000
887       1  30.0000
888       3  23.4500
889       1  30.0000
890       3   7.7500

[891 rows x 2 columns]

In [112]:
# pclass==3인 데이터만 추출해보기
datasets[datasets['pclass']==3]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S  Third   
2           1       3  female  26.0      0      0   7.9250        S  Third   
4           0       3    male  35.0      0      0   8.0500        S  Third   
5           0       3    male   NaN      0      0   8.4583        Q  Third   
7           0       3    male   2.0      3      1  21.0750        S  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
882         0       3  female  22.0      0      0  10.5167        S  Third   
884         0       3    male  25.0      0      0   7.0500        S  Third   
885         0       3  female  39.0      0      5  29.1250        Q  Third   
888         0       3  female   NaN      1      2  23.4500        S  Third   
890         0       3    male  32.0      0      0   7.7500        Q  Third   

       who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0      man        True  NaN  Southampton    no  False       32.0          2  
2    woman       False  NaN  Southampton   yes   True       36.0          1  
4      man        True  NaN  Southampton    no   True       45.0          1  
5      man        True  NaN   Queenstown    no   True        NaN          1  
7    child       False  NaN  Southampton    no  False       12.0          5  
..     ...         ...  ...          ...   ...    ...        ...        ...  
882  woman       False  NaN  Southampton    no   True       32.0          1  
884    man        True  NaN  Southampton    no   True       35.0          1  
885  woman       False  NaN   Queenstown    no  False       49.0          6  
888  woman       False  NaN  Southampton    no  False        NaN          4  
890    man        True  NaN   Queenstown    no   True       42.0          1  

[491 rows x 17 columns]

In [114]:
# pclass==3인 sex, who확인하고 싶다면?
datasets[datasets['pclass']==3][['sex','who']]

sex    who
0      male    man
2    female  woman
4      male    man
5      male    man
7      male  child
..      ...    ...
882  female  woman
884    male    man
885  female  woman
888  female  woman
890    male    man

[491 rows x 2 columns]

In [115]:
# 정수인덱스를 활용할경우
datasets[datasets['pclass']==3].iloc[:,[2,9]]

sex    who
0      male    man
2    female  woman
4      male    man
5      male    man
7      male  child
..      ...    ...
882  female  woman
884    male    man
885  female  woman
888  female  woman
890    male    man

[491 rows x 2 columns]

In [128]:
# 나이가 60 이상인 정보만 출력한다면? (pclass, survived, who만 출력 loc[]사용해서)
datasets[datasets['age']>=60].loc[:,['pclass','survived','who']]

pclass  survived    who
33        2         0    man
54        1         0    man
96        1         0    man
116       3         0    man
170       1         0    man
252       1         0    man
275       1         1  woman
280       3         0    man
326       3         0    man
366       1         1  woman
438       1         0    man
456       1         0    man
483       3         1  woman
493       1         0    man
545       1         0    man
555       1         0    man
570       2         1    man
587       1         1    man
625       1         0    man
630       1         1    man
672       2         0    man
684       2         0    man
694       1         0    man
745       1         0    man
829       1         1  woman
851       3         0    man

여러 복합조건을 이용해서 boolean index를 만들 수 있다
- & : and
- | : or
- ! : not

In [130]:
# 나이가 60보다 크고 선실등급이 1등급이고, 성별이 여자인 데이터만 출력한다면?
up_60 = datasets['age']>60
pclass_1=datasets['pclass']==1
sex_f = datasets['sex']=="female"

datasets[up_60&pclass_1&sex_f]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
275         1       1  female  63.0      1      0  77.9583        S  First   
829         1       1  female  62.0      0      0  80.0000      NaN  First   

       who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
275  woman       False    D  Southampton   yes  False       73.0          2  
829  woman       False    B          NaN   yes   True       72.0          1

In [132]:
# 승객의 평균 나이를 구한다면?
print("승객의 평균 나이 : ",datasets['age'].mean())

승객의 평균 나이 :  29.69911764705882


In [139]:
# 여성 승객의 평균나이를 구한다면?
print("여성 승객의 평균 나이 : ",datasets.loc[datasets['sex']=="female",'age'].mean())
# loc[] 사용 안하는 경우:  datasets[age][datasets['sex']=="female"].mean() 

여성 승객의 평균 나이 :  27.915708812260537


In [144]:
# 1등급 선실의 여성승객의 평균나이를 구한다면?
print("1등급 선실의 여성승객의 평균나이 : ",datasets.loc[(datasets['sex']=="female") & (datasets['pclass']== 1),'age'].mean() )
# loc[] 사용 안하는 경우: datasets['age'][(datasets['pclass']==1)&(datasets['sex']=='female')].mean()

1등급 선실의 여성승객의 평균나이 :  34.61176470588235


## 정렬
- sort_index : 인덱스를 정렬하여 행 또는 열을 정렬한다.
- sort_values : 열의 값을 기준으로 행을 정렬한다.

In [145]:
sort_frm = pd.DataFrame(np.random.randint(0,10,(6,4)))
sort_frm

0  1  2  3
0  0  4  1  0
1  2  7  8  6
2  1  7  3  4
3  6  0  2  3
4  6  6  5  8
5  8  3  8  7

In [148]:
# pd.date_range(날짜,periods=기간)원하는 기간의 날짜를 만들어주는 함수
sort_frm.index=pd.date_range('20210901', periods=6) 
sort_frm.columns=["A","B","C","D"]
sort_frm

A  B  C  D
2021-09-01  0  4  1  0
2021-09-02  2  7  8  6
2021-09-03  1  7  3  4
2021-09-04  6  0  2  3
2021-09-05  6  6  5  8
2021-09-06  8  3  8  7

In [151]:
# 인덱스와 칼럼 섞기
random_date=np.random.permutation(sort_frm.index) 
random_date
r_sort_frm=sort_frm.reindex(index=random_date,
                           columns=["B","A","D","C"])
r_sort_frm


B  A  D  C
2021-09-01  4  0  0  1
2021-09-04  0  6  3  2
2021-09-03  7  1  4  3
2021-09-06  3  8  7  8
2021-09-02  7  2  6  8
2021-09-05  6  6  8  5

In [157]:
# sort_index(axis=, ascending=) ascending=False: 내림차순
r_sort_frm.sort_index(axis=0,ascending=False) # 행을 내림차순으로 정렬

B  A  D  C
2021-09-06  3  8  7  8
2021-09-05  6  6  8  5
2021-09-04  0  6  3  2
2021-09-03  7  1  4  3
2021-09-02  7  2  6  8
2021-09-01  4  0  0  1

In [158]:
# sort_values(by=, ascending=)
r_sort_frm.sort_values(by=["B","A"],ascending= False)

B  A  D  C
2021-09-02  7  2  6  8
2021-09-03  7  1  4  3
2021-09-05  6  6  8  5
2021-09-01  4  0  0  1
2021-09-06  3  8  7  8
2021-09-04  0  6  3  2

In [160]:
# 타이타닉에서 승객의 나이를 기준으로 내림차순 정렬을 한다면?
datasets.sort_values(by='age',ascending=False)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
630         1       1    male  80.0      0      0  30.0000        S  First   
851         0       3    male  74.0      0      0   7.7750        S  Third   
493         0       1    male  71.0      0      0  49.5042        C  First   
96          0       1    male  71.0      0      0  34.6542        C  First   
116         0       3    male  70.5      0      0   7.7500        Q  Third   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
859         0       3    male   NaN      0      0   7.2292        C  Third   
863         0       3  female   NaN      8      2  69.5500        S  Third   
868         0       3    male   NaN      0      0   9.5000        S  Third   
878         0       3    male   NaN      0      0   7.8958        S  Third   
888         0       3  female   NaN      1      2  23.4500        S  Third   

       who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
630    man        True    A  Southampton   yes   True       90.0          1  
851    man        True  NaN  Southampton    no   True       84.0          1  
493    man        True  NaN    Cherbourg    no   True       81.0          1  
96     man        True    A    Cherbourg    no   True       81.0          1  
116    man        True  NaN   Queenstown    no   True       80.5          1  
..     ...         ...  ...          ...   ...    ...        ...        ...  
859    man        True  NaN    Cherbourg    no   True        NaN          1  
863  woman       False  NaN  Southampton    no  False        NaN         11  
868    man        True  NaN  Southampton    no   True        NaN          1  
878    man        True  NaN  Southampton    no   True        NaN          1  
888  woman       False  NaN  Southampton    no  False        NaN          4  

[891 rows x 17 columns]

In [170]:
# 타이타닉중 승객에 대해서 성별의 인원수, 나이별 인원수, 선실별 인원수, 사망/생존별 인원수를 구한다면?
# 성별 인원수
print("성별 인원수: \n", datasets['sex'].value_counts().sort_values())
# 나이별 인원수
print("나이별 인원수: \n", datasets['age'].value_counts().sort_values(ascending=True))
# 선실별 인원수
print("선실별 인원수: \n", datasets['pclass'].value_counts().sort_values(ascending=True))
# 사망/생존별 인원수
print("사망/생존별 인원수: \n", datasets['alive'].value_counts().sort_values())

성별 인원수: 
 female    314
male      577
Name: sex, dtype: int64
나이별 인원수: 
 12.00     1
24.50     1
66.00     1
20.50     1
0.67      1
         ..
19.00    25
28.00    25
18.00    26
22.00    27
24.00    30
Name: age, Length: 88, dtype: int64
선실별 인원수: 
 2    184
1    216
3    491
Name: pclass, dtype: int64
사망/생존별 인원수: 
 yes    342
no     549
Name: alive, dtype: int64


In [172]:
# 타이타닉에서 승객의 나이를 기준으로 내림차순 정렬을 하고 순위를 부여한다면?
rank=datasets.sort_values(by='age',ascending=False)['age'].rank(ascending=False)
rank

630    1.0
851    2.0
493    3.5
96     3.5
116    5.0
      ... 
859    NaN
863    NaN
868    NaN
878    NaN
888    NaN
Name: age, Length: 891, dtype: float64

In [175]:
datasets['rank']=rank
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  \
0    man        True  NaN  Southampton    no  False       32.0          2   
1  woman       False    C    Cherbourg   yes  False       48.0          2   
2  woman       False  NaN  Southampton   yes   True       36.0          1   
3  woman       False    C  Southampton   yes  False       45.0          2   
4    man        True  NaN  Southampton    no   True       45.0          1   

    rank  
0  497.0  
1  183.0  
2  404.5  
3  226.5  
4  226.5

In [179]:
name_dataset=pd.read_csv('C:/Users/whgud/data/year2020_baby_name.csv')
print("type:",type(name_dataset))
name_dataset.head()

type: <class 'pandas.core.frame.DataFrame'>


NAME GENDER  COUNT
0  Isabella      F  22731
1    Sophia      F  20477
2      Emma      F  17179
3    Olivia      F  16860
4       Ava      F  15300

In [181]:
sort_name_dataset=name_dataset.sort_values(by='COUNT',ascending=False) # COUNT칼럼을 기준으로 내림차순 정렬
sort_name_dataset.head()

NAME GENDER  COUNT
0      Isabella      F  22731
19698     Jacob      M  21875
1        Sophia      F  20477
19699     Ethan      M  17866
2          Emma      F  17179

In [184]:
sort_name_dataset.reset_index(inplace=True) # 인덱스 초기화
sort_name_dataset.head()

index      NAME GENDER  COUNT
0      0  Isabella      F  22731
1  19698     Jacob      M  21875
2      1    Sophia      F  20477
3  19699     Ethan      M  17866
4      2      Emma      F  17179

In [190]:
# index열 삭제
#del sort_name_dataset['index']
sort_name_dataset.drop(['index'], axis=1, inplace=True)
sort_name_dataset

NAME GENDER  COUNT
0      Isabella      F  22731
1         Jacob      M  21875
2        Sophia      F  20477
3         Ethan      M  17866
4          Emma      F  17179
...         ...    ...    ...
33833  Mccauley      F      5
33834     Mazal      F      5
33835    Mayzee      F      5
33836    Maythe      F      5
33837     Zzyzx      M      5

[33838 rows x 3 columns]

In [191]:
rank_series=sort_name_dataset['COUNT'].rank(ascending=False)
rank_series

0            1.0
1            2.0
2            3.0
3            4.0
4            5.0
          ...   
33833    31407.5
33834    31407.5
33835    31407.5
33836    31407.5
33837    31407.5
Name: COUNT, Length: 33838, dtype: float64

In [193]:
rank=rank_series.astype('int64') # rank를 정수화해준 것.
sort_name_dataset['rank']= rank # rank 칼럼 추가
sort_name_dataset

NAME GENDER  COUNT   rank
0      Isabella      F  22731      1
1         Jacob      M  21875      2
2        Sophia      F  20477      3
3         Ethan      M  17866      4
4          Emma      F  17179      5
...         ...    ...    ...    ...
33833  Mccauley      F      5  31407
33834     Mazal      F      5  31407
33835    Mayzee      F      5  31407
33836    Maythe      F      5  31407
33837     Zzyzx      M      5  31407

[33838 rows x 4 columns]

In [196]:
# 성별에 따라 각각의 dataframe으로 분할해서 새로운 변수에 저장
m_gender_frm=sort_name_dataset[sort_name_dataset['GENDER']=="M"]
f_gender_frm=sort_name_dataset[sort_name_dataset['GENDER']=="F"]
m_gender_frm.head()

NAME GENDER  COUNT  rank
1    Jacob      M  21875     2
3    Ethan      M  17866     4
5  Michael      M  17133     6
6   Jayden      M  17030     7
7  William      M  16870     8