# Numpy실습

## [실습 01] - ratings.dat

In [9]:
# data 불러오기
# loadtxt()  : 텍스트 파일 로딩
# delimiter  : 필드 구분자
# dtype      : 자료형
import numpy as np
# 배열정보를 확인하기 위한 함수 정의
def aryInfo(ary):
    print('type       :{}'.format(type(ary)))
    print('shape      :{}'.format(ary.shape)) 
    print('dimension  :{}'.format(ary.ndim))  # 몇차원의 배열인지
    print('dtype      :{}'.format(ary.dtype)) # 데이터 타입
    print('Array Data :\n',ary)
    
data = np.loadtxt('C:/Users/whgud/data/ratings.dat' , delimiter = "::", dtype=np.int64)
aryInfo(data)

type       :<class 'numpy.ndarray'>
shape      :(1000209, 4)
dimension  :2
dtype      :int64
Array Data :
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [14]:
# 사용자id::영화id::평점::timestamp(날짜)

# 데이터의 첫 5 행만 확인
print("첫 5행:\n",data[:5,:])
# 데이터의 형태 확인
print("형태 확인:\n",data.shape)


첫 5행:
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
형태 확인:
 (1000209, 4)


In [15]:
# 전체 평균 평점 계산
# data[ : , 2] 전체 행, 2번 열
print("전체 평균 평점 :" , np.mean(data[:,2]))

전체 평균 평점 : 3.581564453029317


In [64]:
# 사용자 아이디 수집
# 전체 행 , 0번 열
user_ids=np.unique(data[:,0]) # 사용자 아이디 리스트(중복X)


id_rating_list=[]
#사용자별 평점 확인을 위한 코드 구문 작성
for user_id in user_ids :
    data_users=data[data[:,0]==user_id,:] # 예를 들어 현재 user_id가 1이라면 user_id가 1인 행들만 추출
    id_rating_mean=np.mean(data_users[:,2]) # 2번째 인덱스(평점)에 해당하는 값의 평균값
    id_rating_list.append([user_id, id_rating_mean])
         
print(id_rating_list[:5])
id_rating_ary = np.array(id_rating_list,np.float64)
print(id_rating_ary[:5])# 사용자 아이디별 평점 확인

   


[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466]]
[[1.         4.18867925]
 [2.         3.71317829]
 [3.         3.90196078]
 [4.         4.19047619]
 [5.         3.14646465]]


In [66]:
# 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기 
aryInfo(id_rating_ary)
id_rating_ary[id_rating_ary[:,1]>=4.0,:]

type       :<class 'numpy.ndarray'>
shape      :(6040, 2)
dimension  :2
dtype      :float64
Array Data :
 [[1.00000000e+00 4.18867925e+00]
 [2.00000000e+00 3.71317829e+00]
 [3.00000000e+00 3.90196078e+00]
 ...
 [6.03800000e+03 3.80000000e+00]
 [6.03900000e+03 3.87804878e+00]
 [6.04000000e+03 3.57771261e+00]]


array([[1.00000000e+00, 4.18867925e+00],
       [4.00000000e+00, 4.19047619e+00],
       [7.00000000e+00, 4.32258065e+00],
       ...,
       [6.02700000e+03, 4.25000000e+00],
       [6.03200000e+03, 4.13461538e+00],
       [6.03400000e+03, 4.09523810e+00]])

In [115]:
# [실습 02]

import csv                  
f_seoul = open('C:/Users/whgud/data/seoul.csv','r')
seoul = csv.reader(f_seoul, delimiter=',')
s_header = next(seoul)
print(s_header)
f_daegu = open('C:/Users/whgud/data/daegu.csv','r')
daegu = csv.reader(f_daegu, delimiter=',')
d_header = next(daegu)


# 1. 기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은 언제였고, 몇도인가요?
max_temp = -999               # 최고 기온을 저장할 변수 초기화
max_date = ''                 # 최고 기온이었던 날짜를 저장할 변수 초기화

for row in seoul :
    if row[-1] == '' :        # 만약 데이터가 누락되었다면 최고 기온을 -999로 저장
        row[-1] = -999
    row[-1] = float(row[-1])  # 문자열로 저장된 최고 기온 값을 실수로 변환
    if max_temp < row[-1] :   # 만약 지금까지 최고 기온보다 더 높다면 업데이트
        max_date = row[0]
        max_temp = row[-1]
f_seoul.close()
print("기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은", max_date,"였고, ",max_temp,"도입니다.")





['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은 2018-08-01 였고,  39.6 도입니다.


In [114]:
# 2. 역사적으로 일교차가 가장 큰 날짜는 몇년 몇월 몇일 인가요?
f_seoul = open('C:/Users/whgud/data/seoul.csv','r')
seoul = csv.reader(f_seoul, delimiter=',')
s_header = next(seoul)

f_daegu = open('C:/Users/whgud/data/daegu.csv','r')
daegu = csv.reader(f_daegu, delimiter=',')
d_header = next(daegu)

max_temp=0
min_temp=0
max_temp_diff=0
date=''

for row in seoul:
    if row[4] == '':
        row[4] = 0
    if row[3] == '':
        row[3] = 0
    row[3]=float(row[3])
    row[4]=float(row[4])
    temp_diff=row[4]-row[3]
    if max_temp_diff < temp_diff:
        date=row[0]
        max_temp_diff=temp_diff
f_seoul.close()
print("역사적으로 서울 지역의 일교차가 가장 큰 날짜는 ",date,"이고, 일교차는 ",max_temp_diff,"입니다")

for row in daegu:
    if row[4] == '':
        row[4] = 0
    if row[3] == '':
        row[3] = 0
    row[3]=float(row[3])
    row[4]=float(row[4])
    temp_diff=row[4]-row[3]
    if max_temp_diff < temp_diff:
        date=row[0]
        max_temp_diff=temp_diff
f_daegu.close()
print("역사적으로 대구 지역의 일교차가 가장 큰 날짜는 ",date,"이고, 일교차는 ",max_temp_diff,"입니다")



역사적으로 서울 지역의 일교차가 가장 큰 날짜는  1942-04-19 이고, 일교차는  21.8 입니다
역사적으로 대구 지역의 일교차가 가장 큰 날짜는  1913-04-04 이고, 일교차는  26.2 입니다


In [124]:
# 3. 1년 중 평균적으로 일교차가 가장 큰 날짜는 몇월 몇일 인가요?
f_seoul = open('C:/Users/whgud/data/seoul.csv','r')
seoul = csv.reader(f_seoul, delimiter=',')
s_header = next(seoul)

f_daegu = open('C:/Users/whgud/data/daegu.csv','r')
daegu = csv.reader(f_daegu, delimiter=',')
d_header = next(daegu)

seoul=np.array(seoul,dtype="U")
aryInfo(seoul)
print(np.unique(seoul[:,0]))
# max_temp=0
# min_temp=0
# max_temp_diff=0
# date=''

# for row in seoul:
    
    
# f_seoul.close()
print("역사적으로 서울 지역의 1년 중 평균적으로 일교차가 가장 큰 날짜는 ",date,"이고, 일교차는 ",max_temp_diff,"입니다")
    

type       :<class 'numpy.ndarray'>
shape      :()
dimension  :0
dtype      :<U42
Array Data :


IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

In [ ]:
# 4. 가장 덥다고 알려진 대구보다 서울이 더 더운날이 가장 많은 연도는 언제인가요?

In [130]:
f_seoul = open('C:/Users/whgud/data/seoul.csv','r')
seoul = csv.reader(f_seoul, delimiter=',')
s_header = next(seoul)

f_daegu = open('C:/Users/whgud/data/daegu.csv','r')
daegu = csv.reader(f_daegu, delimiter=',')
d_header = next(daegu)

data= np.hstack([seoul,daegu])
aryInfo(data)
data[:4]

type       :<class 'numpy.ndarray'>
shape      :(2,)
dimension  :1
dtype      :object
Array Data :


array([<_csv.reader object at 0x0000029780DF9DC0>,
       <_csv.reader object at 0x0000029780DF9940>], dtype=object)