# Numpy실습

## [실습 01] - ratings.dat

In [4]:
# data 불러오기
# loadtxt()  : 텍스트 파일 로딩
# delimiter  : 필드 구분자
# dtype      : 자료형
import numpy as np
# 배열정보를 확인하기 위한 함수 정의
def aryInfo(ary):
    print('type       :{}'.format(type(ary)))
    print('shape      :{}'.format(ary.shape)) 
    print('dimension  :{}'.format(ary.ndim))  # 몇차원의 배열인지
    print('dtype      :{}'.format(ary.dtype)) # 데이터 타입
    print('Array Data :\n',ary)
    
data = np.loadtxt('C:/Users/whgud/data/ratings.dat' , delimiter = "::", dtype=np.int64)
aryInfo(data)

type       :<class 'numpy.ndarray'>
shape      :(1000209, 4)
dimension  :2
dtype      :int64
Array Data :
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [5]:
# 사용자id::영화id::평점::timestamp(날짜)

# 데이터의 첫 5 행만 확인
print("첫 5행:\n",data[:5,:])
# 데이터의 형태 확인
print("형태 확인:\n",data.shape)


첫 5행:
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
형태 확인:
 (1000209, 4)


In [6]:
# 전체 평균 평점 계산
# data[ : , 2] 전체 행, 2번 열
print("전체 평균 평점 :" , np.mean(data[:,2]))

전체 평균 평점 : 3.581564453029317


In [7]:
# 사용자 아이디 수집
# 전체 행 , 0번 열
user_ids=np.unique(data[:,0]) # 사용자 아이디 리스트(중복X)


id_rating_list=[]
#사용자별 평점 확인을 위한 코드 구문 작성
for user_id in user_ids :
    data_users=data[data[:,0]==user_id,:] # 예를 들어 현재 user_id가 1이라면 user_id가 1인 행들만 추출
    id_rating_mean=np.mean(data_users[:,2]) # 2번째 인덱스(평점)에 해당하는 값의 평균값
    id_rating_list.append([user_id, id_rating_mean])
         
print(id_rating_list[:5])
id_rating_ary = np.array(id_rating_list,np.float64)
print(id_rating_ary[:5])# 사용자 아이디별 평점 확인

   


[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466]]
[[1.         4.18867925]
 [2.         3.71317829]
 [3.         3.90196078]
 [4.         4.19047619]
 [5.         3.14646465]]


In [9]:
# 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기 
aryInfo(id_rating_ary)
upper_id=id_rating_ary[id_rating_ary[:,1]>=4.0,:]

type       :<class 'numpy.ndarray'>
shape      :(6040, 2)
dimension  :2
dtype      :float64
Array Data :
 [[1.00000000e+00 4.18867925e+00]
 [2.00000000e+00 3.71317829e+00]
 [3.00000000e+00 3.90196078e+00]
 ...
 [6.03800000e+03 3.80000000e+00]
 [6.03900000e+03 3.87804878e+00]
 [6.04000000e+03 3.57771261e+00]]


In [10]:
# # 계산 결과를 csv 파일로 저장하기
np.savetxt('test.csv', upper_id, fmt='%.1f', delimiter=',' )

In [11]:
# [실습 02]

import csv                  
f_seoul = open('C:/Users/whgud/data/seoul.csv','r')
seoul = csv.reader(f_seoul, delimiter=',')
s_header = next(seoul)
print(s_header)
f_daegu = open('C:/Users/whgud/data/daegu.csv','r')
daegu = csv.reader(f_daegu, delimiter=',')
d_header = next(daegu)


# 1. 기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은 언제였고, 몇도인가요?
max_temp = -999               # 최고 기온을 저장할 변수 초기화
max_date = ''                 # 최고 기온이었던 날짜를 저장할 변수 초기화

for row in seoul :
    if row[-1] == '' :        # 만약 데이터가 누락되었다면 최고 기온을 -999로 저장
        row[-1] = -999
    row[-1] = float(row[-1])  # 문자열로 저장된 최고 기온 값을 실수로 변환
    if max_temp < row[-1] :   # 만약 지금까지 최고 기온보다 더 높다면 업데이트
        max_date = row[0]
        max_temp = row[-1]
f_seoul.close()
print("기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은", max_date,"였고, ",max_temp,"도입니다.")





['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은 2018-08-01 였고,  39.6 도입니다.


In [12]:
# 2. 역사적으로 일교차가 가장 큰 날짜는 몇년 몇월 몇일 인가요?
f_seoul = open('C:/Users/whgud/data/seoul.csv','r')
seoul = csv.reader(f_seoul, delimiter=',')
s_header = next(seoul)

f_daegu = open('C:/Users/whgud/data/daegu.csv','r')
daegu = csv.reader(f_daegu, delimiter=',')
d_header = next(daegu)

max_temp=0
min_temp=0
max_temp_diff=0
date=''

for row in seoul:
    if row[4] == '':
        row[4] = 0
    if row[3] == '':
        row[3] = 0
    row[3]=float(row[3])
    row[4]=float(row[4])
    temp_diff=row[4]-row[3]
    if max_temp_diff < temp_diff:
        date=row[0]
        max_temp_diff=temp_diff
f_seoul.close()
print("역사적으로 서울 지역의 일교차가 가장 큰 날짜는 ",date,"이고, 일교차는 ",max_temp_diff,"입니다")

for row in daegu:
    if row[4] == '':
        row[4] = 0
    if row[3] == '':
        row[3] = 0
    row[3]=float(row[3])
    row[4]=float(row[4])
    temp_diff=row[4]-row[3]
    if max_temp_diff < temp_diff:
        date=row[0]
        max_temp_diff=temp_diff
f_daegu.close()
print("역사적으로 대구 지역의 일교차가 가장 큰 날짜는 ",date,"이고, 일교차는 ",max_temp_diff,"입니다")



역사적으로 서울 지역의 일교차가 가장 큰 날짜는  1942-04-19 이고, 일교차는  21.8 입니다
역사적으로 대구 지역의 일교차가 가장 큰 날짜는  1913-04-04 이고, 일교차는  26.2 입니다


In [34]:
# 3. 1년 중 평균적으로 일교차가 가장 큰 날짜는 몇월 몇일 인가요?
seoul = np.loadtxt('C:/Users/whgud/data/seoul.csv' , delimiter = ",", dtype=np.str, skiprows=1)

day_list = []
day = []
for d in seoul:
    d[0] = d[0][5:] # 월-일만.
    if d[3] == '':
        d[3] = -20
    if d[4] == '':
        d[4] = -20
    temp = float(d[4]) - float(d[3])
    day_list.append([d[0], float(temp)])
    if d[0] not in day:
        day.append(d[0])
day_list = np.array(day_list)

day_mean = []
for d in day:
    temp = day_list[day_list[:,0]==d, 1].astype(np.float).mean()
    day_mean.append([d, temp])
day_mean = np.array(day_mean)
day_max = np.array(day_mean)[:,1].astype(np.float).argmax()
result_list=day_mean[day_max, :]
print("역사적으로 서울 지역의 1년 중 평균적으로 일교차가 가장 큰 날짜는 ",result_list[0],"이고, 일교차는 ",result_list[1],"입니다")




<ipython-input-34-8fa04cf19293>:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  seoul = np.loadtxt('C:/Users/whgud/data/seoul.csv' , delimiter = ",", dtype=np.str, skiprows=1)
<ipython-input-34-8fa04cf19293>:20: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  temp = day_list[day_list[:,0]==d, 1].astype(np.float).mean()


역사적으로 서울 지역의 1년 중 평균적으로 일교차가 가장 큰 날짜는  04-29 이고, 일교차는  11.740178571428572 입니다


<ipython-input-34-8fa04cf19293>:23: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  day_max = np.array(day_mean)[:,1].astype(np.float).argmax()


In [36]:
daegu = np.loadtxt('C:/Users/whgud/data/daegu.csv' , delimiter = ",", dtype=np.str, skiprows=1)

day_list = []
day = []
for d in daegu:
    d[0] = d[0][5:] # 월-일만.
    if d[3] == '':
        d[3] = -20
    if d[4] == '':
        d[4] = -20
    temp = float(d[4]) - float(d[3])
    day_list.append([d[0], float(temp)])
    if d[0] not in day:
        day.append(d[0])
day_list = np.array(day_list)

day_mean = []
for d in day:
    temp = day_list[day_list[:,0]==d, 1].astype(np.float).mean()
    day_mean.append([d, temp])
day_mean = np.array(day_mean)
day_max = np.array(day_mean)[:,1].astype(np.float).argmax()
result_list=day_mean[day_max, :]
result_list
print("역사적으로 대구 지역의 1년 중 평균적으로 일교차가 가장 큰 날짜는 ",result_list[0],"이고, 일교차는 ",result_list[1],"입니다")


<ipython-input-36-d528bd360409>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  daegu = np.loadtxt('C:/Users/whgud/data/daegu.csv' , delimiter = ",", dtype=np.str, skiprows=1)
<ipython-input-36-d528bd360409>:19: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  temp = day_list[day_list[:,0]==d, 1].astype(np.float).mean()


역사적으로 대구 지역의 1년 중 평균적으로 일교차가 가장 큰 날짜는  04-19 이고, 일교차는  12.703508771929824 입니다


<ipython-input-36-d528bd360409>:22: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  day_max = np.array(day_mean)[:,1].astype(np.float).argmax()


In [41]:
# 4. 가장 덥다고 알려진 대구보다 서울이 더 더운날이 가장 많은 연도는 언제인가요?
seoul = np.loadtxt('C:/Users/whgud/data/seoul.csv' , delimiter = ",", dtype=np.str, skiprows=1)
daegu = np.loadtxt('C:/Users/whgud/data/daegu.csv' , delimiter = ",", dtype=np.str, skiprows=1)


for x in seoul: # null값이 경우 초기화
    if x[4]=='':
        x[4]=-20
for x in daegu:
    if x[4]=='':
        x[4]=-20
        
winner = []

for d in seoul:
    t = daegu[daegu[:,0]==d[0], 4]
    if (float(d[4]) > float(t) and t!='-20'):
        winner.append(d[0][:4]) # 연도만 winner에 append
winner = np.array(winner)
(a, b) = np.unique(winner, return_counts=True)
print(a ,len(a))
print(b, len(b))
c = b.argmax()


print("대구보다 서울이 더 더운날이 가장 많은 연도는 ",a[c],"년 입니다")

<ipython-input-41-02e9d0499d33>:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  seoul = np.loadtxt('C:/Users/whgud/data/seoul.csv' , delimiter = ",", dtype=np.str, skiprows=1)
<ipython-input-41-02e9d0499d33>:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  daegu = np.loadtxt('C:/Users/whgud/data/daegu.csv' , delimiter = ",", dtype=np.str, skiprows=1)


['1907' '1908' '1909' '1910' '1911' '1912' '1913' '1914' '1915' '1916'
 '1917' '1918' '1919' '1920' '1921' '1922' '1923' '1924' '1925' '1926'
 '1927' '1928' '1929' '1930' '1931' '1932' '1933' '1934' '1935' '1936'
 '1937' '1938' '1939' '1940' '1941' '1942' '1943' '1944' '1945' '1946'
 '1947' '1948' '1949' '1950' '1953' '1954' '1955' '1956' '1957' '1958'
 '1959' '1960' '1961' '1962' '1963' '1964' '1965' '1966' '1967' '1968'
 '1969' '1970' '1971' '1972' '1973' '1974' '1975' '1976' '1977' '1978'
 '1979' '1980' '1981' '1982' '1983' '1984' '1985' '1986' '1987' '1988'
 '1989' '1990' '1991' '1992' '1993' '1994' '1995' '1996' '1997' '1998'
 '1999' '2000' '2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008'
 '2009' '2010' '2011' '2012' '2013' '2014' '2015' '2016' '2017' '2018'
 '2019' '2020'] 112
[  1   7  52  81  71  50  67  64  46 119  94  98 103 115 121  78  91  98
 102  78  92  95 107 133 122 104  64  61  78  79 107  89 109  94 122  83
 132  80  94 106  77 119 106  88   1  97  88  81  80 